// Generated by CoffeeScript 2.7.0
(function() {
  // classes.coffee
  // CoffeeScript class syntax, inheritance, and a few useful patterns
  // run with: coffee classes.coffee

  // basic class
  // @ in the constructor is shorthand for this.
  // constructor: (@name, @year) is the same as writing:
  //   constructor: (name, year) ->
  //     this.name = name
  //     this.year = year
  var CompiledLanguage, Language, Registry, Serialisable, VersionedLanguage, applyMixin, c, catalogue, coffee, i, j, lang, len, len1, oldest, python, rust, ts;

  Language = class Language {
    constructor(name1, year1) {
      this.name = name1;
      this.year = year1;
    }

    describe() {
      return `${this.name} has been around since ${this.year}.`;
    }

    age() {
      return 2025 - this.year;
    }

  };

  python = new Language("Python", 1991);

  console.log(python.describe()); // => Python has been around since 1991.

  console.log(python.age()); // => 34

  
    // inheritance
  // extends works the same as in JavaScript
  // super() calls the same method on the parent class
  CompiledLanguage = class CompiledLanguage extends Language {
    constructor(name, year, compilesTo) {
      super(name, year);
      this.compilesTo = compilesTo;
    }

    describe() {
      var base;
      base = super.describe();
      return `${base} It compiles down to ${this.compilesTo}.`;
    }

  };

  coffee = new CompiledLanguage("CoffeeScript", 2009, "JavaScript");

  console.log(coffee.describe());

  // => CoffeeScript has been around since 2009. It compiles down to JavaScript.
  console.log(coffee.age()); // => 16, inherited from Language, no override needed

  Registry = (function() {
    
      // class-level (static) variables and methods
    // @ on a property or method inside the class body means it belongs to the
    // class itself, not to instances of it
    class Registry {
      static register(lang) {
        return Registry.all.push(lang);
      }

      static count() {
        return Registry.all.length;
      }

    };

    Registry.all = [];

    return Registry;

  }).call(this);

  Registry.register("C");

  Registry.register("Java");

  Registry.register("Rust");

  console.log(Registry.count()); // => 3

  console.log(Registry.all); // => [ 'C', 'Java', 'Rust' ]

  
  // mixins
  // CoffeeScript doesn't have a built-in mixin keyword but you can
  // copy methods onto a class prototype with a small helper
  Serialisable = {
    toJSON: function() {
      return JSON.stringify({
        name: this.name,
        year: this.year
      });
    },
    fromKey: function() {
      return `${this.name}-${this.year}`;
    }
  };

  applyMixin = function(target, mixin) {
    var key, results, val;
    results = [];
    for (key in mixin) {
      val = mixin[key];
      results.push(target.prototype[key] = val);
    }
    return results;
  };

  applyMixin(Language, Serialisable);

  rust = new Language("Rust", 2015);

  console.log(rust.toJSON()); // => {"name":"Rust","year":2015}

  console.log(rust.fromKey()); // => Rust-2015

  
    // versioned language subclass
  VersionedLanguage = class VersionedLanguage extends Language {
    constructor(name, year, version) {
      super(name, year);
      this.version = version;
    }

    fullName() {
      return `${this.name} v${this.version}`;
    }

    isModern() {
      return this.year >= 2010;
    }

  };

  ts = new VersionedLanguage("TypeScript", 2012, "5.4");

  console.log(ts.fullName()); // => TypeScript v5.4

  console.log(ts.isModern()); // => true

  c = new VersionedLanguage("C", 1972, "C23");

  console.log(c.fullName()); // => C vC23

  console.log(c.isModern()); // => false

  
  // putting it all together
  catalogue = [new Language("FORTRAN", 1957), new Language("C", 1972), new Language("C++", 1985), new Language("Python", 1991), new Language("Java", 1995), new Language("JavaScript", 1995), new Language("Ruby", 1995), new Language("CoffeeScript", 2009), new Language("Rust", 2015)];

  console.log("\nbefore 1990:");

  for (i = 0, len = catalogue.length; i < len; i++) {
    lang = catalogue[i];
    if (lang.year < 1990) {
      console.log(`  ${lang.name} (${lang.year})`);
    }
  }

  console.log("\nafter 2000:");

  for (j = 0, len1 = catalogue.length; j < len1; j++) {
    lang = catalogue[j];
    if (lang.year > 2000) {
      console.log(`  ${lang.name} (${lang.year})`);
    }
  }

  oldest = catalogue.reduce(function(a, b) {
    if (a.year < b.year) {
      return a;
    } else {
      return b;
    }
  });

  console.log(`\noldest in the list: ${oldest.name} (${oldest.year})`);

}).call(this);
