// Generated by CoffeeScript 2.7.0
(function() {
  // main.coffee
  // drives the whole page: tab switching, source loading, and dynamic content
  // compile with: coffee --compile main.coffee

  // ── data ──────────────────────────────────────────────────────

  // all the syntax comparison rows, kept here instead of hardcoded in HTML
  var btn, buildFileList, buildInstallBox, buildReadme, buildSyntaxTable, buttons, currentTab, el, esc, installSteps, j, len, loadSource, panels, repoFiles, showTab, syntaxRows, tabOrder;

  syntaxRows = [["Function", "const f = (x) => x * 2", "f = (x) -> x * 2"], ["Bound function", "const f = () => this.val", "f = => @val"], ["String interpolation", "`Hello ${name}`", '"Hello #{name}"'], ["List comprehension", "arr.map(x => x * 2)", "(x * 2 for x in arr)"], ["Existence check", "x !== null && x !== undefined", "x?"], ["Array slice", "arr.slice(1, 4)", "arr[1..3]"], ["Conditional", "if (x > 0) { ... }", "if x > 0  # no braces"], ["Unless", "if (!condition) { ... }", "unless condition"], ["Default param", "function f(x = 0) {}", "f = (x = 0) ->"], ["this.prop", "this.name", "@name"], ["Class property", "this.count = 0", "@count = 0"], ["Existential assign", "x = x !== null ? x : 'default'", "x ?= 'default'"]];

  // files shown in the file list widget
  repoFiles = [
    {
      icon: "☕",
      name: "main.coffee",
      desc: "tab switching, dynamic content, source loading"
    },
    {
      icon: "☕",
      name: "examples.coffee",
      desc: "15 annotated examples of core features"
    },
    {
      icon: "☕",
      name: "compare.coffee",
      desc: "CoffeeScript source next to the compiled JS"
    },
    {
      icon: "☕",
      name: "classes.coffee",
      desc: "classes, inheritance, static methods, mixins"
    },
    {
      icon: "📄",
      name: "main.js",
      desc: "compiled from main.coffee"
    },
    {
      icon: "📄",
      name: "examples.js",
      desc: "compiled from examples.coffee"
    },
    {
      icon: "📄",
      name: "compare.js",
      desc: "compiled from compare.coffee"
    },
    {
      icon: "📄",
      name: "classes.js",
      desc: "compiled from classes.coffee"
    },
    {
      icon: "🎨",
      name: "style.css",
      desc: "all styles"
    },
    {
      icon: "📖",
      name: "README.md",
      desc: "readme and docs"
    }
  ];

  // shell commands shown in the install box
  installSteps = [
    {
      comment: "# install CoffeeScript (requires Node.js)",
      cmd: "npm install -g coffeescript"
    },
    {
      comment: "# run a file directly",
      cmd: "coffee examples.coffee"
    },
    {
      comment: "# compile to JavaScript",
      cmd: "coffee --compile examples.coffee"
    },
    {
      comment: "# watch and recompile on save",
      cmd: "coffee --compile --watch examples.coffee"
    }
  ];

  // ── helpers ───────────────────────────────────────────────────

  // create an element with optional className and innerHTML
  el = function(tag, cls, html) {
    var node;
    node = document.createElement(tag);
    if (cls) {
      node.className = cls;
    }
    if (html) {
      node.innerHTML = html;
    }
    return node;
  };

  esc = function(str) {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  };

  // ── build syntax table ─────────────────────────────────────────
  buildSyntaxTable = function() {
    var cs, feature, j, js, len, results, tbody, tr;
    tbody = document.querySelector('.compare-table tbody');
    if (tbody == null) {
      return;
    }
    tbody.innerHTML = '';
    results = [];
    for (j = 0, len = syntaxRows.length; j < len; j++) {
      [feature, js, cs] = syntaxRows[j];
      tr = document.createElement('tr');
      tr.innerHTML = `<td>${esc(feature)}</td>
<td><code>${esc(js)}</code></td>
<td><code>${esc(cs)}</code></td>`;
      results.push(tbody.appendChild(tr));
    }
    return results;
  };

  // ── build file list ────────────────────────────────────────────
  buildFileList = function() {
    var container, file, header, item, j, len, results;
    container = document.querySelector('.file-list');
    if (container == null) {
      return;
    }
    // keep the header, rebuild the items
    header = container.querySelector('.file-list-header');
    container.innerHTML = '';
    if (header) {
      container.appendChild(header);
    }
    results = [];
    for (j = 0, len = repoFiles.length; j < len; j++) {
      file = repoFiles[j];
      item = el('div', 'file-list-item');
      item.innerHTML = `<span class="icon">${file.icon}</span>
<span class="filename">${esc(file.name)}</span>
<span class="desc">${esc(file.desc)}</span>`;
      results.push(container.appendChild(item));
    }
    return results;
  };

  // ── build install box ──────────────────────────────────────────
  buildInstallBox = function() {
    var box, comment, i, j, len, results, step;
    box = document.querySelector('.install-box');
    if (box == null) {
      return;
    }
    box.innerHTML = '';
    results = [];
    for (i = j = 0, len = installSteps.length; j < len; i = ++j) {
      step = installSteps[i];
      comment = el('span', 'comment', esc(step.comment));
      box.appendChild(comment);
      box.appendChild(document.createElement('br'));
      box.appendChild(document.createTextNode(step.cmd));
      if (i !== installSteps.length - 1) {
        box.appendChild(document.createElement('br'));
        results.push(box.appendChild(document.createElement('br')));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  // ── tab switching ──────────────────────────────────────────────
  buttons = document.querySelectorAll('nav button');

  panels = document.querySelectorAll('.tab-panel');

  showTab = function(name) {
    var btn, j, k, len, len1, panel, ref, ref1;
    for (j = 0, len = panels.length; j < len; j++) {
      panel = panels[j];
      panel.classList.remove('active');
    }
    for (k = 0, len1 = buttons.length; k < len1; k++) {
      btn = buttons[k];
      btn.classList.remove('active');
    }
    if ((ref = document.getElementById(`tab-${name}`)) != null) {
      ref.classList.add('active');
    }
    return (ref1 = document.querySelector(`nav button[data-tab='${name}']`)) != null ? ref1.classList.add('active') : void 0;
  };

  for (j = 0, len = buttons.length; j < len; j++) {
    btn = buttons[j];
    (function(btn) {
      return btn.addEventListener('click', function() {
        var tab;
        tab = btn.getAttribute('data-tab');
        if (tab != null) {
          showTab(tab);
          if (tab === 'examples' || tab === 'compare' || tab === 'classes') {
            return loadSource(tab);
          }
        }
      });
    })(btn);
  }

  // keyboard: left/right arrows move between tabs
  tabOrder = ['overview', 'examples', 'compare', 'classes', 'readme'];

  currentTab = function() {
    var active;
    active = document.querySelector('nav button.active');
    return active != null ? active.getAttribute('data-tab') : void 0;
  };

  document.addEventListener('keydown', function(e) {
    var idx, next, prev, ref;
    if ((ref = e.target.tagName) === 'INPUT' || ref === 'TEXTAREA') {
      return;
    }
    idx = tabOrder.indexOf(currentTab());
    if (e.key === 'ArrowRight' && idx < tabOrder.length - 1) {
      next = tabOrder[idx + 1];
      showTab(next);
      if (next === 'examples' || next === 'compare' || next === 'classes') {
        loadSource(next);
      }
    }
    if (e.key === 'ArrowLeft' && idx > 0) {
      prev = tabOrder[idx - 1];
      showTab(prev);
      if (prev === 'examples' || prev === 'compare' || prev === 'classes') {
        return loadSource(prev);
      }
    }
  });

  // ── source file loading ────────────────────────────────────────
  // fetches the raw .coffee file and drops it into the code block
  // highlight.js re-runs on the element after content is set
  loadSource = function(name) {
    el = document.getElementById(`code-${name}`);
    if (el == null) {
      return;
    }
    if (el.dataset.loaded === 'true') {
      return;
    }
    return fetch(`${name}.coffee`).then(function(res) {
      if (!res.ok) {
        throw new Error(`${res.status}`);
      }
      return res.text();
    }).then(function(src) {
      el.textContent = src;
      el.dataset.loaded = 'true';
      return hljs.highlightElement(el);
    }).catch(function(err) {
      return el.textContent = `could not load ${name}.coffee (${err.message})`;
    });
  };

  // ── readme tab: render a mini version inline ───────────────────
  buildReadme = function() {
    var code, container, desc, h, item, k, l, label, len1, len2, li, p, pre, ref, results, section, sections, tag, ul;
    container = document.getElementById('readme-body');
    if (container == null) {
      return;
    }
    sections = [
      {
        heading: "What is CoffeeScript?",
        level: 2,
        body: `CoffeeScript is a small language that compiles to JavaScript.
You write <code>.coffee</code> files, run the compiler, and get
plain <code>.js</code> files back.`
      },
      {
        heading: null,
        body: `Jeremy Ashkenas built it in 2009. It was widely used from about
2012 to 2016, before ES6 brought most of its ideas into JavaScript itself.`
      },
      {
        heading: "Files",
        level: 3,
        list: ["main.coffee: tab switching and dynamic content",
      "examples.coffee: annotated examples of core features",
      "compare.coffee: CoffeeScript source next to the compiled JS",
      "classes.coffee: classes, inheritance, static methods, mixins"]
      },
      {
        heading: "Running the code",
        level: 3,
        pre: "npm install -g coffeescript\ncoffee examples.coffee\ncoffee --compile examples.coffee"
      },
      {
        heading: "References",
        level: 3,
        body: 'Ashkenas, J. <em>CoffeeScript: Accelerated JavaScript Development.</em> Pragmatic Bookshelf, 2011.'
      },
      {
        heading: null,
        body: '<a href="https://coffeescript.org" style="color:#0969da;">coffeescript.org</a>'
      }
    ];
    results = [];
    for (k = 0, len1 = sections.length; k < len1; k++) {
      section = sections[k];
      if (section.heading) {
        tag = section.level === 2 ? 'h2' : 'h3';
        h = document.createElement(tag);
        h.style.cssText = section.level === 2 ? 'font-size:1.4rem; margin-bottom:0.75rem; margin-top:1.5rem;' : 'font-size:1.05rem; font-weight:600; margin:1.25rem 0 0.4rem;';
        h.textContent = section.heading;
        container.appendChild(h);
      }
      if (section.body) {
        p = el('p', null, section.body);
        p.style.margin = '0.5rem 0';
        container.appendChild(p);
      }
      if (section.list) {
        ul = document.createElement('ul');
        ul.style.cssText = 'padding-left:1.5rem; margin:0.5rem 0;';
        ref = section.list;
        for (l = 0, len2 = ref.length; l < len2; l++) {
          item = ref[l];
          li = document.createElement('li');
          li.style.margin = '0.25rem 0';
          [label, desc] = item.split(': ');
          li.innerHTML = `<code style=\"background:#f6f8fa;border:1px solid #d0d7de;border-radius:3px;padding:0.1em 0.35em;font-size:0.85em;\">${esc(label)}</code>: ${esc(desc)}`;
          ul.appendChild(li);
        }
        container.appendChild(ul);
      }
      if (section.pre) {
        pre = document.createElement('pre');
        pre.style.cssText = 'background:#f6f8fa;border:1px solid #d0d7de;border-radius:6px;padding:0.75rem 1rem;font-size:0.85rem;overflow-x:auto;margin:0.75rem 0;';
        code = document.createElement('code');
        code.textContent = section.pre;
        pre.appendChild(code);
        results.push(container.appendChild(pre));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  // ── init ──────────────────────────────────────────────────────
  buildSyntaxTable();

  buildFileList();

  buildInstallBox();

  buildReadme();

  showTab('overview');

  loadSource('examples'); // pre-load so it's ready when user clicks the tab

}).call(this);
